version: "3"

services: 
    app:
        build: 
            context: .
        ports: 
         - "8000:8000"
        volumes: 
         - ./app:/app
        command: >
         sh -c "cd app && python checker.py check_in mochis"
